### ISSUE TITLE
Option to disable or hide the alpha channel slider

### ISSUE THREAD

**Issue by H0rn0chse** [ivanvmat/color-picker#1]
Hi,

Is it possible that you might add an option to the configuration to disable or preferably hide the alpha channel slider?
Currently I'm hiding it in a hard coded css way:
https://github.com/H0rn0chse/GifBuilder/blob/main/styles/options.css#L50

Thanks in advance.

**Comment by ivanvmat** [comment]
Hi,

I'm added use_alpha option in color picker configuration
`const picker = new ColorPickerControl({ 
    container: document.body, 
    use_alpha: false
});`
In the next version I will add the ability to change this parameter dynamically.

**Comment by ivanvmat** [comment]
Hi,

I added use_alpha option in color picker configuration
const picker = new ColorPickerControl({ container: document.body, use_alpha: false });
In the next version I will add the ability to change this parameter dynamically.

**Comment by ivanvmat** [comment]
Hi,

I added use_alpha option in color picker configuration
`const picker = new ColorPickerControl({ container: document.body, use_alpha: false });`
In the next version I will add the ability to change this parameter dynamically.

**Comment by ivanvmat** [comment]
Hi,

I added use_alpha option to the configuration.
`const picker = new ColorPickerControl({ container: document.body, use_alpha: false });`
In the next version I will add the ability to change this parameter dynamically.

**Comment by H0rn0chse** [comment]
Thank you very much
I've tested the new version and it works perfectly for me!
